version: '3.8'

services:
  runner:
    build:
      context: ./Docker Image
      dockerfile: Dockerfile.linux
    platform: linux/x64
    restart: always
    environment:
      - REG_URL=<reg-url>
      - REG_TOKEN=<reg-token-for-self-hosted-runner>
      - NAME=<runner-name>
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.4'
          memory: 256M
